### ISSUE TITLE
LBR-Stack: ROS 2 and Python Integration of KUKA FRI for Med and IIWA Robots

### ISSUE THREAD

**Issue by mhubii** [oss-for-surgtech/workshop-hamlyn2024#3]
@cmower, @tvercaut, @cbergeles

## Personal Details
* First author:
  * [x] family-names: Huber
  * [x] given-names: Martin
  * [x] email: martin.huber@kcl.ac.uk
  * [x] Department/Faculty: School of Biomedical Engineering & Imaging Sciences
  * [x] affiliation: King's College London
* Second author:
  * [x] family-names: Mower 
  * [x] given-names: Christopher E.
  * [x] email: mower.chris@gmail.com
  * [x] Department/Faculty: Former School of Biomedical Engineering & Imaging Sciences
  * [x] affiliation: Former King's College London
* Third author:
  * [x] family-names: Vercauteren 
  * [x] given-names: Tom
  * [x] email: tom.vercauteren@kcl.ac.uk
  * [x] Department/Faculty: School of Biomedical Engineering & Imaging Sciences
  * [x] affiliation: King's College London
* Fourth author:
  * [x] family-names: Bergeles 
  * [x] given-names: Christos
  * [x] email: christos.bergeles@kcl.ac.uk
  * [x] Department/Faculty: School of Biomedical Engineering & Imaging Sciences
  * [x] affiliation: King's College London

## Which subtheme most closely connects to your poster?
* [x] Open-source software libraries and frameworks, 
* [ ] Medical and surgical software innovations,
* [ ] Sustainability in open-source software,
* [ ] Case studies showcasing novel applications and combinations of existing software,
* [ ] Protocols for managing clinical data in computer-assisted software for surgical technologies, and 
* [ ] Project summaries, methodological approaches, research findings, and initiatives related to Open-Source Software for Surgical Technologies.
* [ ] Other (please add topic).

## Poster title
LBR-Stack: ROS 2 and Python Integration of KUKA FRI for Med and IIWA Robots

Source code: https://github.com/lbr-stack/lbr_fri_ros2_stack/
Poster draft: https://docs.google.com/presentation/d/1HCWLj45a1Wz0ztmfNr6DS-eROC0UJkhI1CJPOICt-pU/edit?usp=sharing

## Briefly describe your poster proposal
The KUKA LBR series (IIWA and Med) is a widely adopted platform in both industry and research, especially in the medical field where the medical variants of the IIWA are licensed for integration into medical products. Despite their extensive use, particularly in research, other collaborative robots (cobots), such as the more cost-effective Franka Emika Pandas, have gained significant traction in data-driven applications. This increased adoption of the Panda cobots can be partially attributed to their large and active user community, which facilitates code sharing and collaboration, thereby enhancing research efforts.

In contrast, the community support for the KUKA LBR series has been less robust, largely due to fragmented drivers across various programming languages (Java, Matlab, and C++) and poor backward compatibility. The LBR-Stack aims to resolve these issues by offering a streamlined software architecture that integrates KUKA’s FRI client SDK with ROS 2. This architecture ensures backward compatibility with all versions of the FRI, thereby consolidating a larger segment of the user community and promoting research collaboration. This development was enabled by KUKA’s decision to permit the redistribution of the FRI library starting from version 1.11.

**Comment by mxochicale** [comment]
Dear @mhubii 

Please refer to [Zenodo DOI's for accepted poster](https://github.com/oss-for-surgtech/workshop-hamlyn2024/tree/main/posters#zenodo-dois-for-accepted-poster) for further details on Zenodo submission! We have sent you an email with further details of our workshop, please do not hesitate to reach via this issue of emails if there is anything else we can help!

Looking forward to meeting you!
Thanks, @evaherbst @thompson318, and @mxochicale

**Comment by mxochicale** [comment]
Publication is under review but in the meantime please refer to the GitHub repository https://github.com/lbr-stack/lbr_fri_ros2_stack and pre-print in arXiv: [https://arxiv.org/abs/2311.12709​](https://arxiv.org/abs/2311.12709)

If you have further questions, please contact author martin.huber@kcl.ac.uk​.
