### ISSUE TITLE
dVRK-Si: The Next Generation da Vinci Research Kit

### ISSUE THREAD

**Issue by pkazanzides** [oss-for-surgtech/workshop-hamlyn2024#4]
## :school_satchel: Poster submission
Welcome to Poster submission for 🎒 Open-Source Software for Surgical Technologies :tada:	 

## Personal Details
* First author:
  * [ ] family-names: Xu
  * [ ] given-names:  Keshuai
  * [ ] email: keshuai@jhu.edu
  * [ ] orcid: optional 
  * [ ] Department/Faculty Computer Science
  * [ ] affiliation: Johns Hopkins University
* Second author:
  * [ ] family-names:  Wu
  * [ ] given-names:   Jie Ying
  * [ ] email:  JieYing.Wu@vanderbilt.edu
  * [ ] orcid: optional 
  * [ ] Department/Faculty  Computer Science
  * [ ] affiliation:  Vanderbilt University
* Third author:
  * [ ] family-names: Deguet
  * [ ] given-names:  Anton
  * [ ] email: anton.deguet@jhu.edu
  * [ ] orcid: optional 
  * [ ] Department/Faculty Computer Science
  * [ ] affiliation: Johns Hopkins University
* Fourth author:
  * [ ] family-names: Kazanzides
  * [ ] given-names:  Peter
  * [ ] email: pkaz@jhu.edu
  * [ ] orcid: optional 
  * [ ] Department/Faculty Computer Science
  * [ ] affiliation: Johns Hopkins University

* Please copy and paste above lines to add more authors

## Which subtheme most closely connects to your poster?
* [X] Open-source software libraries and frameworks, 
* [ ] Medical and surgical software innovations,
* [ ] Sustainability in open-source software,
* [ ] Case studies showcasing novel applications and combinations of existing software,
* [ ] Protocols for managing clinical data in computer-assisted software for surgical technologies, and 
* [ ] Project summaries, methodological approaches, research findings, and initiatives related to Open-Source Software for Surgical Technologies.
* [ ] Other (please add topic).

## Poster title
 dVRK-Si: The Next Generation da Vinci Research Kit

## Briefly describe your poster proposal

The da Vinci Research Kit (dVRK) is an open-source and open-hardware surgical robotics research platform that provides complete access to all levels of control on decommissioned da Vinci Surgical Systems. The original dVRK, released to the research community in 2012 and now installed at more than 40 institutions worldwide, is based on the first-generation da Vinci system. We present dVRK-Si, an update that extends support to decommissioned second/third generation da Vinci S/Si patient-side robots. We describe extensions to the system architecture that maintain compatibility and interoperability with the original dVRK system, thereby enabling a heterogeneous mix of dVRK and dVRK-Si arms in the same system.

**Comment by mxochicale** [comment]
Dear @pkazanzides  

Thank you for your submission! We are pleased to inform you that your poster has been accepted.

Please refer to [Zenodo DOI's for accepted poster](https://github.com/oss-for-surgtech/workshop-hamlyn2024/tree/main/posters#zenodo-dois-for-accepted-poster) for further details on Zenodo submission! We have sent you an email with further details of our workshop, please do not hesitate to reach via this issue of emails if there is anything else we can help!

Looking forward to meeting you!
Thanks, @evaherbst @thompson318, and @mxochicale

**Comment by pkazanzides** [comment]
Uploaded poster to Zenodo:  https://doi.org/10.5281/zenodo.12537886

**Comment by mxochicale** [comment]
Many thanks [pkazanzides](https://github.com/pkazanzides), we will link your work to the main README and get it touch soon to share final summary of what we achieved!  Miguel
