### ISSUE TITLE
OptimUS: an open-source fast full-wave solver for calculating acoustic wave propagation with applications in biomedical ultrasound

### ISSUE THREAD

**Issue by SRHaqshenas** [oss-for-surgtech/workshop-hamlyn2024#5]
## :school_satchel: Poster submission
Welcome to Poster submission for 🎒 Open-Source Software for Surgical Technologies :tada:	 

## Personal Details
* First author:
  * [ ] family-names: Haqshenas
  * [ ] given-names: Reza
  * [x] email: r.haqshenas@ucl.ac.uk
  * [ ] orcid: optional 
  * [ ] Department/Faculty: Mechanical Engineering
  * [ ] affiliation: University College London 
* Second author:
  * [ ] family-names: Gélat
  * [ ] given-names: Pierre
  * [ ] email: p.gelat@ucl.ac.uk
  * [ ] orcid: optional 
  * [ ] Department/Faculty: Division of Surgery and Interventional Sciences
  * [ ] affiliation: University College London
* Third author:
  * [ ] family-names: van't Wout
  * [ ] given-names: Elwin
  * [ ] email: e.wout@uc.cl
  * [ ] orcid: optional 
  * [ ] Department/Faculty: Institute for Mathematical and Computational Engineering
  * [ ] affiliation: Pontificia Universidad Cat ́olica de Chile
 
## Which subtheme most closely connects to your poster?
* [X] Open-source software libraries and frameworks, 
* [X] Medical and surgical software innovations,
* [ ] Sustainability in open-source software,
* [ ] Case studies showcasing novel applications and combinations of existing software,
* [ ] Protocols for managing clinical data in computer-assisted software for surgical technologies, and 
* [ ] Project summaries, methodological approaches, research findings, and initiatives related to Open-Source Software for Surgical Technologies.
* [ ] Other (please add topic).

## Poster title
OptimUS: an open-source fast full-wave solver for calculating acoustic wave propagation with applications in biomedical ultrasound

## Briefly describe your poster proposal
Focused ultrasound is an emerging technology with significant potential for targeted and selective interventions in the body. It utilises focused ultrasonic energy to induce biological effects in target tissues. Achieving successful clinical outcomes requires developing a patient-specific treatment plan by solving the forward wave propagation problem for various ultrasound excitation parameters. We have developed fast numerical techniques using Boundary Element Methods (BEM) and implemented them in an open-source Python package named [OptimUS](https://github.com/optimuslib/optimus). This poster presents the main features of the latest version of OptimUS, including generalised and multiple BEM formulations and different parallelisation methods, and numerical simulations using anatomical meshes for various therapeutic applications.

**Comment by mxochicale** [comment]
Dear @SRHaqshenas 

Thank you for your submission! We are pleased to inform you that your poster has been accepted.

Please refer to [Zenodo DOI's for accepted poster](https://github.com/oss-for-surgtech/workshop-hamlyn2024/tree/main/posters#zenodo-dois-for-accepted-poster) for further details on Zenodo submission! We have sent you an email with further details of our workshop, please do not hesitate to reach via this issue or email if there is anything else we can help!

Looking forward to meeting you!
Thanks, @evaherbst @thompson318, and @mxochicale

**Comment by mxochicale** [comment]
Shared poster by https://zenodo.org/records/12720943

**Comment by mxochicale** [comment]
We will update main readme to link posters and provide further visibility of poster authors
